site_name: Vcnone's Wiki
site_author: 'VC'
site_description: '恒以致远'
site_url: 'https://wiki.vcnone.top/'

nav:
- 主页: index.md
- 开发工具:
  - Git: tools/Git.md
  - NVM-Windows: tools/NVM-Windows.md
  - Python:
    - Install: tools/Python-Install.md
    - pip: tools/Python-pip.md
- 网站博客:
  - LNMP:
    - Install: website/LNMP-Install.md
    - nginx: website/Nginx-Config.md
  - Hexo:
    - Local: website/Hexo-Local.md
    - GithubPage: website/Hexo-GithubPage.md
  - Supervisor: website/Supervisor.md
  - Syncthing: website/Syncthing.md
- 关于我: about.md

theme:
  name: material

plugins:
  - search:
      separator: '[\s\u200b\-]'





