site_name: Vcnone's Wiki
site_author: 'VC'
site_description: '恒以致远'
site_url: 'https://wiki.vcnone.top/'

nav:
- Index: index.md
- Hexo: 
    - Local: Hexo-Local.md
    - GithubPage: Hexo-GithubPage.md
- Sever:
    - LNMP: LNMP搭建.md
    - Supervisor: Supervisor.md
    - Syncthing: Syncthing.md
    - Python:
      - pip: Python-pip.md
- About: about.md

theme:
  name: material






