site_name: Vcnone's Wiki
site_author: 'VC'
site_description: '恒以致远'
site_url: 'https://wiki.vcnone.top/'

nav:
- 主页: index.md
- 开发工具:
  - Git: Git.md
  - NVM-Windows: NVM-Windows.md
  - Python:
    - Install: Python-Install.md
    - pip: Python-pip.md
- 网站博客:
  - LNMP:
    - Install: LNMP-Install.md
    - nginx: Nginx-Config.md
  - Hexo:
    - Local: Hexo-Local.md
    - GithubPage: Hexo-GithubPage.md
  - Supervisor: Supervisor.md
  - Syncthing: Syncthing.md
- 关于我: about.md

theme:
  name: material

plugins:
  - search:
      separator: '[\s\u200b\-]'





